name: erpnext-v15
services:
  backend:
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: phalouvas/swissmed-worker:version-15
    networks:
      bench-network: null
      mariadb-network: null
    pull_policy: missing
    restart: unless-stopped
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
  backup:
    command:
      - bench --site all backup
    entrypoint:
      - bash
      - -c
    image: phalouvas/swissmed-worker:version-15
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
  configurator:
    command:
      - |
        ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache "redis://$$REDIS_CACHE"; bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; bench set-config -g redis_socketio "redis://$$REDIS_QUEUE"; bench set-config -gp socketio_port $$SOCKETIO_PORT;
    depends_on:
      redis-cache:
        condition: service_started
        required: true
      redis-queue:
        condition: service_started
        required: true
    entrypoint:
      - bash
      - -c
    environment:
      DB_HOST: mariadb-database
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    image: phalouvas/swissmed-worker:version-15
    networks:
      bench-network: null
      mariadb-network: null
    pull_policy: missing
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
  frontend:
    command:
      - nginx-entrypoint.sh
    depends_on:
      backend:
        condition: service_started
        required: true
      websocket:
        condition: service_started
        required: true
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: app.swissmedhealth.com
      PROXY_READ_TIMEOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: phalouvas/swissmed-worker:version-15
    labels:
      traefik.docker.network: traefik-public
      traefik.enable: "true"
      traefik.http.routers.erpnext-v15-http.entrypoints: http
      traefik.http.routers.erpnext-v15-http.middlewares: https-redirect
      traefik.http.routers.erpnext-v15-http.rule: Host(`app.swissmedhealth.com`)
      traefik.http.routers.erpnext-v15-http.service: erpnext-v15
      traefik.http.routers.erpnext-v15-https.entrypoints: https
      traefik.http.routers.erpnext-v15-https.rule: Host(`app.swissmedhealth.com`)
      traefik.http.routers.erpnext-v15-https.service: erpnext-v15
      traefik.http.routers.erpnext-v15-https.tls: "true"
      traefik.http.routers.erpnext-v15-https.tls.certresolver: le
      traefik.http.services.erpnext-v15.loadbalancer.server.port: "8080"
      traefik.port: "8084"
    networks:
      bench-network: null
      traefik-public: null
    ports:
      - mode: ingress
        target: 8080
        published: "8084"
        protocol: tcp
    pull_policy: missing
    restart: unless-stopped
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
  queue-long:
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: phalouvas/swissmed-worker:version-15
    networks:
      bench-network: null
      mariadb-network: null
    pull_policy: missing
    restart: unless-stopped
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
  queue-short:
    command:
      - bench
      - worker
      - --queue
      - short,default
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: phalouvas/swissmed-worker:version-15
    networks:
      bench-network: null
      mariadb-network: null
    pull_policy: missing
    restart: unless-stopped
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
  redis-cache:
    image: redis:6.2-alpine
    networks:
      bench-network: null
      mariadb-network: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: redis-cache-data
        target: /data
        volume: {}
  redis-queue:
    image: redis:6.2-alpine
    networks:
      bench-network: null
      mariadb-network: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: redis-queue-data
        target: /data
        volume: {}
  scheduler:
    command:
      - bench
      - schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: phalouvas/swissmed-worker:version-15
    networks:
      bench-network: null
      mariadb-network: null
    pull_policy: missing
    restart: unless-stopped
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
  websocket:
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: phalouvas/swissmed-worker:version-15
    networks:
      bench-network: null
      mariadb-network: null
    pull_policy: missing
    restart: unless-stopped
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
networks:
  bench-network:
    name: erpnext-v15
  mariadb-network:
    name: mariadb-network
    external: true
  traefik-public:
    name: traefik-public
    external: true
volumes:
  redis-cache-data:
    name: erpnext-v15_redis-cache-data
  redis-queue-data:
    name: erpnext-v15_redis-queue-data
  sites:
    name: erpnext-v15_sites
x-backend-defaults:
  depends_on:
    configurator:
      condition: service_completed_successfully
  image: phalouvas/swissmed-worker:version-15
  pull_policy: if_not_present
  volumes:
    - sites:/home/frappe/frappe-bench/sites
x-customizable-image:
  image: phalouvas/swissmed-worker:version-15
  pull_policy: if_not_present
x-depends-on-configurator:
  depends_on:
    configurator:
      condition: service_completed_successfully
